In [23]:
import pandas as pd

# Leer el archivo Excel
df_excel = pd.read_excel('top sunedu universidades.xlsx')
df_excel

                                   University  Ranking  Indicator
0        Universidad Peruana Cayetano Heredia   100.00   2.909446
1    Pontificia Universidad Católica del Perú    78.25   2.709910
2    Universidad Nacional Mayor de San Marcos    54.72   2.623386
3          Universidad Nacional de Ingeniería    25.30   1.507663
4      Universidad Nacional Agraria La Molina    24.90   1.181543
..                                        ...      ...        ...
89   Universidad Nacional José María Arguedas     0.00   0.003732
90         Universidad Nacional de San Martín     0.00   0.744212
91           Universidad Nacional de Frontera     0.00   0.004045
92         Universidad Autónoma de Ica S.A.C.     0.00   0.003090
93                                        NaN     0.00        NaN

[94 rows x 3 columns]

In [24]:
df_excel = df_excel.dropna(subset=['University', 'Ranking', 'Indicator'])

# Calcular la correlación entre las dos últimas columnas
correlation = df_excel['Ranking'].corr(df_excel['Indicator'])

# Imprimir la correlación
print("Correlación entre las dos últimas columnas:", correlation)

Correlación entre las dos últimas columnas: 0.8057823569018411

In [25]:
correlation = 0.8057823569018411  # Reemplaza este valor con el resultado real de la correlación

# Formatear la correlación en formato LaTeX
latex_correlation = f"Correlación entre las dos últimas columnas: {correlation:.4f}"

# Imprimir el resultado en formato LaTeX
print(latex_correlation)

Correlación entre las dos últimas columnas: 0.8058

In [26]:
latex_table = df_excel.to_latex(index=False, caption="DataFrame in LaTeX Format")

# Print the LaTeX table
print(latex_table)

\begin{table}
\centering
\caption{DataFrame in LaTeX Format}
\begin{tabular}{lrr}
\toprule
                                        University &  Ranking &  Indicator \\
\midrule
              Universidad Peruana Cayetano Heredia &   100.00 &   2.909446 \\
          Pontificia Universidad Católica del Perú &    78.25 &   2.709910 \\
          Universidad Nacional Mayor de San Marcos &    54.72 &   2.623386 \\
                Universidad Nacional de Ingeniería &    25.30 &   1.507663 \\
            Universidad Nacional Agraria La Molina &    24.90 &   1.181543 \\
 Universidad Nacional de San Antonio Abad del C... &    23.10 &   1.309439 \\
  Universidad Peruana de Ciencias Aplicadas S.A.C. &    15.65 &   1.043590 \\
   Universidad Nacional de San Agustín de Arequipa &    12.04 &   1.248054 \\
             Universidad Científica del Sur S.A.C. &    12.03 &   0.713784 \\
                  Universidad Nacional de Trujillo &    11.49 &   1.172384 \\
               Universidad de San Martín de Porres &    10.21 &   1.186457 \\
                              Universidad de Piura &     9.20 &   0.985016 \\
                          Universidad del Pacífico &     9.16 &   0.979433 \\
                               Universidad de Lima &     8.54 &   0.871680 \\
            Universidad de Ingeniería y Tecnología &     8.05 &   0.493501 \\
                Universidad Nacional del Altiplano &     7.16 &   0.980616 \\
            Universidad San Ignacio de Loyola S.A. &     6.15 &   0.903723 \\
                         Universidad Ricardo Palma &     5.86 &   0.797986 \\
                                  Universidad ESAN &     5.74 &   0.796409 \\
              Universidad Privada del Norte S.A.C. &     5.36 &   0.950049 \\
          Universidad Nacional Federico Villarreal &     4.77 &   0.994309 \\
               Universidad Católica de Santa María &     4.29 &   0.930542 \\
                 Universidad Nacional de Cajamarca &     3.86 &   0.689607 \\
                    Universidad Católica San Pablo &     3.84 &   0.487395 \\
                     Universidad Nacional de Piura &     3.71 &   0.933259 \\
                    Universidad Continental S.A.C. &     3.61 &   0.463627 \\
          Universidad Nacional Agraria de la Selva &     2.89 &   0.393508 \\
 Asociación Civil Universidad de Ciencias y Hum... &     2.85 &   0.012261 \\
                Universidad Privada Antenor Orrego &     2.79 &   0.785988 \\
       Universidad Nacional Jorge Basadre Grohmann &     2.74 &   0.757595 \\
                   Universidad Nacional del Callao &     2.64 &   0.887623 \\
 Universidad Nacional Toribio Rodríguez de Mend... &     2.50 &   0.702439 \\
   Universidad Nacional Santiago Antúnez de Mayolo &     2.40 &   0.836153 \\
   Universidad Nacional Amazónica de Madre de Dios &     2.19 &   0.018831 \\
                         Universidad Peruana Unión &     1.86 &   0.811155 \\
              Universidad Nacional de Huancavelica &     1.77 &   0.763959 \\
                    Universidad Nacional de Tumbes &     1.54 &   0.743529 \\
      Universidad Privada San Juan Bautista S.A.C. &     1.43 &   0.364012 \\
 Universidad Nacional de Educación Enrique Guzm... &     1.33 &   0.753105 \\
                  Universidad César Vallejo S.A.C. &     1.32 &   1.446523 \\
 Universidad Nacional Micaela Bastidas de Apurímac &     1.19 &   0.333009 \\
             Universidad Católica Sedes Sapientiae &     1.07 &   0.366657 \\
                      Universidad Andina del Cusco &     0.94 &   0.780116 \\
 Universidad Nacional Hermilio Valdizán de Huánuco &     0.80 &   0.806546 \\
               Universidad Antonio Ruiz de Montoya &     0.76 &   0.366178 \\
                   Universidad Nacional de Ucayali &     0.75 &   0.760840 \\
           Universidad Privada Norbert Wiener S.A. &     0.70 &   0.374869 \\
                 Universidad Señor de Sipán S.A.C. &     0.61 &   0.426672 \\
                      Universidad Privada de Tacna &     0.60 &   0.782592 \\
           Universidad Tecnológica del Perú S.A.C. &     0.55 &   0.381438 \\
      Universidad Nacional Tecnológica de Lima Sur &     0.46 &   0.007212 \\
                              Universidad La Salle &     0.39 &   0.350339 \\
              Universidad Autónoma del Perú S.A.C. &     0.37 &   0.670904 \\
                     Universidad Peruana Los Andes &     0.34 &   0.000642 \\
   Universidad Católica Santo Toribio de Mogrovejo &     0.16 &   0.728147 \\
              Universidad María Auxiliadora S.A.C. &     0.00 &   0.334208 \\
                    Universidad Nacional de Cañete &     0.00 &   0.002804 \\
 Universidad Nacional Intercultural de la Selva... &     0.00 &   0.000000 \\
                      Universidad Nacional de Jaén &     0.00 &   0.332967 \\
          Universidad Femenina del Sagrado Corazón &     0.00 &   0.714967 \\
             Universidad para el Desarrollo Andino &     0.00 &   0.000000 \\
 Universidad de Ciencias y Artes de América Lat... &     0.00 &   0.334568 \\
                  Universidad Nacional de Moquegua &     0.00 &   0.350138 \\
   Facultad de Teología Pontificia y Civil de Lima &     0.00 &   0.674826 \\
 Universidad Nacional Autónoma de Tayacaja Dani... &     0.00 &   0.000321 \\
 Universidad Nacional Intercultural Fabiola Sal... &     0.00 &   0.000000 \\
 Universidad Nacional Intercultural de Quillabamba &     0.00 &   0.000000 \\
                Universidad Le Cordon Bleu S.A.C.  &     0.00 &   0.331724 \\
          Universidad Nacional del Centro del Perú &     0.00 &   0.877012 \\
              Universidad Tecnológica de los Andes &     0.00 &   0.338975 \\
                    Universidad Nacional del Santa &     0.00 &   0.798015 \\
                  Universidad Marcelino Champagnat &     0.00 &   0.723500 \\
 Universidad Nacional José Faustino Sánchez Car... &     0.00 &   0.808470 \\
                  Universidad Jaime Bausate y Meza &     0.00 &   0.328880 \\
 Universidad Nacional Autónoma Altoandina de Tarma &     0.00 &   0.000000 \\
 Universidad Privada de Huancayo Franklin Roose... &     0.00 &   0.000000 \\
 Universidad Nacional Intercultural de la Amazonía &     0.00 &   0.004408 \\
                  Universidad Nacional de Barranca &     0.00 &   0.001883 \\
            Universidad Nacional Autónoma de Chota &     0.00 &   0.000642 \\
           Universidad Nacional Autónoma de Huanta &     0.00 &   0.000642 \\
    Universidad Católica de Trujillo Benedicto XVI &     0.00 &   0.384484 \\
       Universidad Nacional Daniel Alcides Carrión &     0.00 &   0.738684 \\
                   Universidad Nacional de Juliaca &     0.00 &   0.002204 \\
    Universidad Nacional Autónoma de Alto Amazonas &     0.00 &   0.000321 \\
                            Universidad de Huánuco &     0.00 &   0.806546 \\
          Universidad Nacional José María Arguedas &     0.00 &   0.003732 \\
                Universidad Nacional de San Martín &     0.00 &   0.744212 \\
                  Universidad Nacional de Frontera &     0.00 &   0.004045 \\
                Universidad Autónoma de Ica S.A.C. &     0.00 &   0.003090 \\
\bottomrule
\end{tabular}
\end{table}

C:\Users\marce\AppData\Local\Temp\ipykernel_39312\1750422402.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  latex_table = df_excel.to_latex(index=False, caption="DataFrame in LaTeX Format")